/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const create_credential: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number) => [number, number, number, number];
export const create_credential_definition: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number) => [number, number, number, number];
export const create_credential_offer: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const create_credential_request: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => [number, number, number, number];
export const create_link_secret: () => [number, number, number, number];
export const create_or_update_revocation_state: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number) => [number, number, number, number];
export const create_presentation: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number) => [number, number, number, number];
export const create_revocation_registry_definition: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number, number];
export const create_revocation_status_list: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: bigint) => [number, number, number, number];
export const create_schema: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
export const create_w3c_credential: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number) => [number, number, number, number];
export const create_w3c_presentation: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number) => [number, number, number, number];
export const credential_from_w3c: (a: number, b: number) => [number, number, number, number];
export const credential_get_attribute: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const credential_to_w3c: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const encode_credential_attributes: (a: number, b: number) => [number, number, number, number];
export const generate_nonce: () => [number, number, number, number];
export const get_tails_file: (a: number, b: number) => [number, number];
export const object_from_json: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const process_credential: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => [number, number, number, number];
export const process_w3c_credential: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => [number, number, number, number];
export const revocation_registry_definition_get_attribute: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const start: () => void;
export const update_revocation_status_list: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: bigint) => [number, number, number, number];
export const update_revocation_status_list_timestamp_only: (a: bigint, b: number, c: number) => [number, number, number, number];
export const verify_presentation: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number) => [number, number, number];
export const verify_w3c_presentation: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number) => [number, number, number];
export const version: () => [number, number];
export const w3c_credential_get_integrity_proof_details: (a: number, b: number) => [number, number, number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
